<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701092130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE clocking_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project VARCHAR(255) NOT NULL, duration INT NOT NULL, clocking_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_331F02BDB6D103F ON clocking_item (clocking_id)');
        $this->addSql('ALTER TABLE clocking_item ADD CONSTRAINT FK_331F02BDB6D103F FOREIGN KEY (clocking_id) REFERENCES clocking (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE clocking_item DROP CONSTRAINT FK_331F02BDB6D103F');
        $this->addSql('DROP TABLE clocking_item');
    }
}
